title: RiSharp's Blog
author: Richard AKA RiSharp AKA RichardPoes
email: richard.poes@outlook.com
description: >-
  Some C# thoughts and other stuff by RichardPoes.
baseurl: ""
url: blog.ririsharper.nl
github_username:  RichardPoes

# Build settings
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
